
# Keymaps
#===============================================
# pane系
#===============================================
# pane move
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# pane split
bind - split-window -v -c "#{pane_current_path}" #-で上下に分割
bind | split-window -h -c "#{pane_current_path}" #|で左右に分割
# kill pane
bind Q confirm-before -p "kill pane?" kill-pane

# prefix + r to reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"

#===============================================
# window系
#===============================================
bind c new-window
bind q confirm-before -p "kill window?" kill-window
bind n next-window
bind p previous-window

#===============================================
# copy mode関連
#===============================================
# copy系
bind y copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# 移動
bind-key -T copy-mode-vi J send-keys -N 10 -X cursor-down
bind-key -T copy-mode-vi K send-keys -N 10 -X cursor-up
bind-key -T copy-mode-vi H send-keys -N 10 -X start-of-line
bind-key -T copy-mode-vi L send-keys -N 10 -X end-of-line

bind-key -T copy-mode-vi w send-keys -N 10 -X next-word
bind-key -T copy-mode-vi b send-keys -N 10 -X previous-word
bind-key -T copy-mode-vi e send-keys -N 10 -X end-of-word
