source-file ~/.config/tmux/conf.d/*.conf

# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# pane系
set -g pane-border-style fg=#3b4261
set -g pane-active-border-style fg=#7aa2f7

# enable mouse
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# copy like vim
setw -g mode-keys vi
set -g set-clipboard on

# status bar
set -g status-interval 1
set -g status-style bg=#1f2335,fg=#c0caf5
# -- 左: セッション名
set -g status-left-length 30
set -g status-left '#[fg=#ffffff,bg=#3b4261,bold] #S #[default]'

# -- 中央: window
set -g window-status-format ' #[fg=#7aa2f7]#I #[fg=#a9b1d6]#W '
set -g window-status-current-format '#[fg=#1f2335,bg=#7aa2f7,bold] #I #W #[default]'

# -- 右: 日時
set -g status-right '#[fg=#a9b1d6]%Y-%m-%d #[fg=#7aa2f7]%H:%M '

# tmuxを起動するたびに環境変数を更新
set -ag update-environment " VSCODE_IPC_HOOK_CLI"
set -ag update-environment " VSCODE_GIT_IPC_HANDLE"
