# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# pane系
set -g pane-border-style fg=#3b4261
set -g pane-active-border-style fg=#7aa2f7
# pane move
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# pane split
bind - split-window -v -c "#{pane_current_path}" #-で上下に分割
bind | split-window -h -c "#{pane_current_path}" #|で左右に分割

# prefix + r to reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# window
bind c new-window
bind x confirm-before -p "kill pane?" kill-pane

# enable mouse
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# copy like vim
setw -g mode-keys vi
set -g set-clipboard on

# status bar
set -g status-interval 1
set -g status-style bg=#1f2335,fg=#c0caf5
# -- 左: セッション名
set -g status-left-length 30
set -g status-left '#[fg=#ffffff,bg=#3b4261,bold] #S #[default]'

# -- 中央: window
set -g window-status-format ' #[fg=#7aa2f7]#I #[fg=#a9b1d6]#W '
set -g window-status-current-format '#[fg=#1f2335,bg=#7aa2f7,bold] #I #W #[default]'

# -- 右: 日時
set -g status-right '#[fg=#a9b1d6]%Y-%m-%d #[fg=#7aa2f7]%H:%M '


